version: '3.3'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./contrib/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
     - internal
     - external
    depends_on:
      - app
    ports:
      - "8080:80"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./:/var/www
    networks:
      - external
      - internal
  db:
    image: mysql:5.6
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - internal
      - external
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=phpdvdprofiler
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - "db-data:/var/lib/mysql"
    ports:
      - '3306:3306'

volumes:
  db-data:
  app-storage:

networks:
  internal:
    internal: true
  external:
    driver: bridge
