name: PHP Syntax Checker

on: [push,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@8.4
